### ISSUE TITLE
Mismatched/Misplaced Parentheses Parser Error

### ISSUE THREAD

**Issue by sanbales** [vinci1it2000/formulas#2]
I get a mismatched or misplaced parenthesis error when trying to parse this expression: `"=0.1234*(A1/1000/(Sheet1!B1*Sheet1!B2))"`

(Actually, this expression fails as well: `"=1000/(Sheet1!B1+Sheet1!B2)"`)

```
---------------------------------------------------------------------------
ParenthesesError                          Traceback (most recent call last)
<ipython-input-4-f6dfb1afa0bf> in <module>()
----> 1 parser.ast(expression="=0.1234*(A1/1000/(Sheet1!B1*Sheet1!B2))")

c:\sandboxes\excel2py\formulas\formulas\parser.py in ast(self, expression, context)
     55             else:
     56                 raise FormulaError(expression)
---> 57         Parenthesis(')').ast(tokens, stack, builder)
     58         tokens = tokens[1:-1]
     59         while stack:

c:\sandboxes\excel2py\formulas\formulas\tokens\parenthesis.py in ast(self, tokens, stack, builder)
     35 
     36             if not stack or self.opens[self.name] != stack[-1].name:
---> 37                 raise ParenthesesError()
     38             token = stack.pop()
     39             if not token.get_check_n(token):

ParenthesesError: Mismatched or misplaced parentheses!
```

Looks like in the parsing, the parenthesis after the `1000` is not being parsed:
`[( <Parenthesis>, 0.1234 <Number>, * <Operator>, ( <Parenthesis>, A1 <Range>, / <Operator>, 1000 <Number>, / <Operator>, (SHEET1!B1 <Range>, * <Operator>, SHEET1!B2 <Range>, ) <Parenthesis>, ) <Parenthesis>, ) <Parenthesis>]`

Maybe because the `/` is perceived as escaping it?

Here is some code that should reproduce the error:
```
from formulas import Parser
parser = Parser()
parser.ast(expression="=0.1234*(A1/1000/(Sheet1!B1*Sheet1!B2))")
```

I'm very impressed with this project, and if you are looking for help, I'd be glad to help and try to figure out this bug.  I've been working on a [fork](https://github.com/sanbales/pycel) of [Pycel](https://github.com/dgorissen/pycel) but this project looks to be in better shape.  At the very least, I can offer to port some of the Excel formulas I have already 'pythonized'.

Cheers!

**Comment by vinci1it2000** [comment]
I discovered the error and I have fixed in 13f7f1c.

The problem was the range token. This was parsing the parenthesis as part of the sheet name. The excel specification says that chars as "(" or ")" are valid for an sheet name. I did a quick check and I discovered that this is valid but the sheet name have to be between commas. The notation without commas, like  `Sheet1!B1`, has some more specifications that are: 

- first char must be a word character ([\w], this include `_`) excluding numbers ([\d]).
- other chars can be any word character including `.` ([\w\.]).

Regarding the 'pythonized' excel formulas... these are welcome! you can push a pull request. But please before pushing add some test case in the `test/test_files/ test.xlsx` file. The 'pythonized' formulas have to be implemented inside package `formulas.formulas.functions`.
